### ISSUE TITLE
Consider using pinniped

### ISSUE THREAD

**Issue by enj** [p0-security/kubernetes-oidc#2]
Hi @nbrahms, I briefly spoke with you and Shashwat after [your presentation at KubeCon NA 2023](https://sched.co/1R2o1), where I recommend you explore using [pinniped](https://pinniped.dev/docs/tutorials/concierge-and-supervisor-demo#why-pinniped) as the mechanism for configuring OIDC in a secure and consistent way across multiple (possibly heterogeneous) Kube clusters.  Let me know if you have any thoughts, and feel free to [provide direct feedback](https://github.com/vmware-tanzu/pinniped/issues) to the current maintainers.

cc @gergas3

**Comment by enj** [comment]
@nbrahms @gergas3 ping regarding above :)

**Comment by gergas3** [comment]
Thanks for calling it to our attention @enj !
The purpose of this repo is to demonstrate the "native" way to provide OIDC in k8s. I'm sure Pinniped can help overcome some of the limitations that exist.

**Comment by enj** [comment]
> The purpose of this repo is to demonstrate the "native" way to provide OIDC in k8s

Nothing prevents Pinniped being used in the native way via the OIDC flags on the API server (it can serve as an OIDC issuer).  You can skip the impersonation proxy altogether but still gain the benefits of a tightly integrated client experience, no token replays, easy addition of new clusters without the creation of OAuth clients, support for non-OIDC IDPs, etc.

I am going to close this issue out since I simply wanted to use it to inform you about Pinniped.  Thanks for your time 🙂
